### ISSUE TITLE
[Request] Spawn ready actors Web API call

### ISSUE THREAD

**Issue by ergoxiv** [Etheirys/Brio#103]
**Is your feature request related to a problem? Please describe:**
In Anamnesis, we discovered that spawned actors via Brio's Web API do not have their respective model object (i.e. Scene::CharacterBase, which inherits from Scene::DrawObject) available right away. Instead, the object seems to become available shortly (usually within 200ms) after Brio has responded to the API request. Specifically, the object becomes available, after it is read from the game process' memory during one of Anamnesis' periodic actor synchronizations, which take place roughly every 33ms.

**Describe the solution you'd like:**
Would it be possible to provide a spawn option for "spawned actor ready" actors, or maybe incorporate it into the usual spawn behaviour? What I mean is that Brio would wait for the spawned actor to complete its initialization/loading before responding to the API request.

**Comment by Minmoose** [comment]
Latest commit should have this fixed. I want to wait to push a build of this until some testing can be done to make sure this doesn't break anything.

**Comment by ergoxiv** [comment]
All good! Thank you for looking into it so quickly for me ❤️
