### ISSUE TITLE
Brio will not export files in GPose.

### ISSUE THREAD

**Issue by JesterlyHermit** [Etheirys/Brio#105]
I exported my characters through Mare several times with no success. I downloaded the MCDF files five times over, yet the Actor (or Actor 'Clone') doesn't change appearance. It does play animations just fine. I get the error to 'redraw' or refresh my character. The files weren't corrupted because they were fine the day before. Anything I can do?

**Comment by Minmoose** [comment]
I'm not observing this, I don't think this is a Brio issue as Brio does not do anything with MCDFs, is it still happening?

**Comment by JesterlyHermit** [comment]
I believe my game was acting weird. When I restarted my computer, the MCDFs
uploaded in Brio.

**Comment by Minmoose** [comment]
Good to hear it's working again!
