### ISSUE TITLE
Brio not loading Penumbra on spawned actors

### ISSUE THREAD

**Issue by kblossom42** [Etheirys/Brio#106]
I'm not sure if this is due to a game update, but somehow I have noticed that any penumbra mods are not being recognized by Brio when used on spawned actors. I've tried reinstalling but that hasn't worked. Is there a known issue for this or something I may have missed?

**Comment by Minmoose** [comment]
@kblossom42 Make sure Penumbra Integration is enabled and Active in Brio's settings
![image](https://github.com/user-attachments/assets/e24c79a8-ec88-463a-904e-0ee55ad86abd)

**Comment by kblossom42** [comment]
> @kblossom42 Make sure Penumbra Integration is enabled and Active in Brio's settings ![image](https://private-user-images.githubusercontent.com/12839703/399412550-e24c79a8-ec88-463a-904e-0ee55ad86abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MjI5OTAsIm5iZiI6MTczNTYyMjY5MCwicGF0aCI6Ii8xMjgzOTcwMy8zOTk0MTI1NTAtZTI0Yzc5YTgtZWM4OC00NjNhLTkwNGUtMGVlNTVhZDg2YWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA1MjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTRjYWYyZTI2OWRkMTFhZjkxYzFhM2QwNjRjMWFkYzdhOWJlYWE3ZDUyMzhlOTQ1YmM0MTQzOGU1NDRjYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s8FOMejvk6TWSkRL7jeBRRPtXpgVrpc-ifs4KXM74d8)

I do have that toggled on and it's unfortunately still not working.

**Comment by Minmoose** [comment]
@kblossom42 Hmm strange, I'm not getting this, does it happen with all mods? Also, can you link to some that do not work?

**Comment by kblossom42** [comment]
> @kblossom42 Hmm strange, I'm not getting this, does it happen with all mods? Also, can you link to some that do not work?

Yep, it happens with all mods. Hairstyles, makeup, clothing, etc.

**Comment by Minmoose** [comment]
Is the collection set to the right one on the Actor? 

![image](https://github.com/user-attachments/assets/49071990-1c5e-4129-8cbf-f5a3e694becc)

**Comment by kblossom42** [comment]
> Is the collection set to the right one on the Actor?
> 
> ![image](https://private-user-images.githubusercontent.com/12839703/399428633-49071990-1c5e-4129-8cbf-f5a3e694becc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzA2NzAsIm5iZiI6MTczNTYzMDM3MCwicGF0aCI6Ii8xMjgzOTcwMy8zOTk0Mjg2MzMtNDkwNzE5OTAtMWM1ZS00MTI5LThjYmYtZjVhM2U2OTRiZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA3MzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTFmNjlhNjdmYTM0ODAwNjE4ZTBlOWFiM2ViMTdmZjlkNWUzMmMwNDRhMzM0NDgxZWJhZTY4ODhhMWMwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zSKUT6Jm8ykDlfz0dCdnKC7fQb3CTxh3LJGQFXukuB4)

Ah that seems to have done the trick. Not sure how that got messed up. Thank you!

**Comment by Minmoose** [comment]
No problem and glad to hear you fixed it!
