### ISSUE TITLE
wet attire doesnt work

### ISSUE THREAD

**Issue by XarXarMinx** [Etheirys/Brio#51]
tried to apply 'Force wet' in glamourer & toggled wet attire in gpose settings, every time i try to take a gpose with brio it removes the effect on my character, i went through the list of status effects and nothing really does it  so figured id report the issue

**Comment by Minmoose** [comment]
Brio overrides the games "Wet Attire" feature, to get the effect back go to the following location in the `Advanced Appearance` screen

![image](https://github.com/Etheirys/Brio/assets/12839703/f1b045ad-8a9f-4c7c-af58-2f1a08fcfab3)

![image](https://github.com/Etheirys/Brio/assets/12839703/86d25beb-b8e2-486b-a56e-ce786cae36eb)
