### ISSUE TITLE
Hair posing issue with Miqo'te

### ISSUE THREAD

**Issue by Ov3rburdened** [Etheirys/Brio#52]
Hair Front Right and Hair Front Left no longer function when posing mine or other Miqo. Tried on multiple hair styles. Worked on Brio before last ffxiv patch.

**Comment by Minmoose** [comment]
I am unable to reproduce this, are you using hair styles mods?

**Comment by Ov3rburdened** [comment]
I am not using any hair mods. The only body modifications I use are Freyja and IVCS aside from a few clothing options.

**Comment by Minmoose** [comment]
I'm marking this as stale and closing, if you are still having this issue, please reopen!
