### ISSUE TITLE
Customize+ and Brio

### ISSUE THREAD

**Issue by Giantnoggin** [Etheirys/Brio#53]
So im not sure if it ever worked for me or not but just barely I noticed that brio does not pick up my C+ settings when I am nude.  Seems to be ok with my top on but as soon as i remove the top and I go into posing it no longer recognizes the settings.  When I disable brio and go into posing the C+ settings are there and do not revert whether I have clothes on or not.  I made sure that I had up to date repos on both Brio and C+I noticed there were 2 repos for Brio, but both have the same version so there was no difference there.  Any help would be greatly appreciated.

**Comment by Minmoose** [comment]
Closing as stale, if your issue presets please open a new issue!
