### ISSUE TITLE
Posing Crash on Crash Test

### ISSUE THREAD

**Issue by Github-Sic** [Etheirys/Brio#55]
Hello and thank you very much for working so hard on this! Posed for a good amount of time yesterday, far longer than it had allowed in a while before crashing once more.  I was posing three different actors, one my character and two Brio generated. All using listed mods and all in human/non transformed form.
https://imgur.com/a/1yjASP3

**Comment by Github-Sic** [comment]
Oops, I can just add the images directly!
![Mod List](https://github.com/Etheirys/Brio/assets/109579388/7e1aa69f-0d30-4d28-9f28-879a02b041ad)
![Dalamud List](https://github.com/Etheirys/Brio/assets/109579388/8253d070-d939-4893-99ab-703f295f0be8)

**Comment by Github-Sic** [comment]
Closed this issue by mistake like an idiot. Images uploaded directly now.
![Dalamud List](https://github.com/Etheirys/Brio/assets/109579388/bd302ee2-b78d-4384-92f8-7c2d6684b7db)
![Mod List](https://github.com/Etheirys/Brio/assets/109579388/11ddde21-5e0d-4b0f-8755-7906b238e969)

**Comment by Minmoose** [comment]
Thank you! I pushed out CrashTest v0.2.3.5, if you could use that and see if it stops the crashing and report back, I would appreciate it!

**Comment by Github-Sic** [comment]
I'll give it more testing, thank you! So far it does seem a lot more stable.

**Comment by Minmoose** [comment]
Duplicate issue, Merged into #46
