### ISSUE TITLE
IPC Third party no longer working

### ISSUE THREAD

**Issue by cekefun** [Etheirys/Brio#58]
I wanna integrate Brio with Penumbra for a picture, but the it shows as inactive, even after reloading.
The same is the case for Glamourer, but Mare seems to work.
![image](https://github.com/Etheirys/Brio/assets/14937306/b15b3761-48fc-4fd6-9c2d-fb9e4c88a452)

**Comment by Minmoose** [comment]
Thanks for the report! Fixed with Brio **v0.3.1.4**.

**Comment by cekefun** [comment]
Works indeed! Thanks!
