### ISSUE TITLE
Pose Export does not save new bones

### ISSUE THREAD

**Issue by grimdour** [Etheirys/Brio#63]
As I was trying to update my library of default poses to include the new face bones, I noticed the new pose files produced are a third of what the previous filesizes were, going from 97kb to around 36-37.

On importing poses, it seems the tool is leaving out the new bones. Fully expected, but worth reporting as an issue anyway.

**Comment by AsgardXIV** [comment]
The bones export (at least for me), but most facial bones now require position mode to be turned on during import, and by default it is off. You'll need to enable it to see them update.

**Comment by grimdour** [comment]
Gotcha, thank you!
