### ISSUE TITLE
[Appearance] Using + on the last hair, causes a crash

### ISSUE THREAD

**Issue by SephArima** [Etheirys/Brio#66]
I was trying out hair styles and was just clicking + till I reach the end and when I clicked it again, the game crashed.
I have tried this with F and M miqo'te. 
F -  after clicking + on the last hair, there were two hairs that just stretches across the screen and crashed on the 2nd one
M - after clicking + on the last hair, it instantly crashes

I have no hair mods.

**Comment by Minmoose** [comment]
This should ™️ now be fixed... 😬

Reopen if it isn't!
