### ISSUE TITLE
Crash to desktop when using Brio

### ISSUE THREAD

**Issue by Glorou** [Etheirys/Brio#69]
Hi there, 

When using Brio after some arbitrary amount of time, I get a crash to desktop. These don't get caught by Dalamud since its an issue with cimgui.dll, this is the stack during the crash. There's no particular behaviour that spawns this crash.
![DbgX Shell_qTm00tcRji](https://github.com/user-attachments/assets/9007fdda-4872-4ed6-9ec5-4d6d44afa5b6)

**Comment by Glorou** [comment]
Specifically for @Minmoose I've uploaded the crashdump to the brio-logs channel in XIV Tools ([direct link here](https://discord.com/channels/748454690118828163/1065528286274392095/1263653693421518899))

**Comment by Minmoose** [comment]
With the changes in 0.4.0 this should be fixed, if not reopen.

Thank you for the report and for the help!
