### ISSUE TITLE
[Request] More specific bone filtering?

### ISSUE THREAD

**Issue by thechocorooms** [Etheirys/Brio#70]
With Dawntrail changing up a lot of things and most notably adding several new bones to character faces, I wondered if it would be possible to filter bones more than "head" and "body"? like "mouth" "eye" "nose" etc. Or if not, to distinguish them in some other way. This is a LOT to pick through.
![ffxiv_dx11_Vg0NSrkSXg](https://github.com/user-attachments/assets/ead810a9-5f6a-4c80-b4c7-58ff2a124da8)

**Comment by Minmoose** [comment]
Should be fixed as of [0.3.3](https://github.com/Etheirys/Brio/releases/tag/v0.3.3),

If the number of Categories added in 0.3.3 was not enough feel free to reopen
