### ISSUE TITLE
[Request] Make Animation Control speed sliders be editable text boxes similar to Model Transform

### ISSUE THREAD

**Issue by leothelion4953** [Etheirys/Brio#77]
The motivation of this change is when doing Gpose with multiple characters, precise speed values are required to synchronize looping animations of different lengths. For example, if animation 1 has 680 frames and animation 2 has 500 frames, I would want to set animation 1 to run at 680/500=1.360 speed and animation 2 to run at 1.000 speed for both animations to synchronize and loop simultaneously in 500 frames.

It is not possible to update the speed values to specific values down to 3 decimal points easily as the current speed sliders changes in steps based on the size of the UI. By changing the controls from sliders to editable text boxes that is still responsive to mouse dragging similar to Model Transform text boxes would be a great quality of life improvement for my use case.

I am not sure if such text box controls have the ability to limit the minimum and maximum values like a slider control to replicate the current behavior. However, the current restriction of 0.000 to 5.000 should be removed to give the user freedom to pick any value, such as negative values to play the animation backwards or large positive values to make funny meme videos.

Thank you for considering my request.

**Comment by Minmoose** [comment]
@leothelion4953 

You can press "Ctrl + Left Click" on any slider in Brio to change any slider into editable text box 

As for a larger maximum value and to allow negative values that will be added in the next update as a "delimit" checkbox next to the speed slider in the Advanced Animation Control window

**Comment by leothelion4953** [comment]
I didn't Ctrl + Left Click is a thing for slider controls. Thanks for the tip, and thanks for the delimit checkbox in the latest update!
