### ISSUE TITLE
Xat attention pop up keep opening

### ISSUE THREAD

**Issue by Candle-Willowmint** [Etheirys/Brio#81]
Hi, 

Every time I connect to the game and also when I enter in gpose, the Xat announcement pop-up appears following the latest update. i don't know if this is normal, I'd like it to stop but don't know if it's possible on my own. I'm on the version v0.4.0.3. 

Thank you for your hard work. 

![image](https://github.com/user-attachments/assets/d8ef1864-76dd-4965-8111-dabb891d6892)

**Comment by SephArima** [comment]
Do you also have XAT on your plugin list? Try uninstalling it

**Comment by Candle-Willowmint** [comment]
> Do you also have XAT on your plugin list? Try uninstalling it

Thank you very much, indeed it was XAT that i still had activated, my bad i didn't think about it at all!
