### ISSUE TITLE
Wetness effect

### ISSUE THREAD

**Issue by CHCOOBOO** [Etheirys/Brio#89]
I found that when Brio is enabled, I can't apply the wetness effect in Gpose setting.
By the way, my Platform is macOS (M1 Mac mini and M2 MacBook Air) , Launcher is XIV on Mac in DXMT mode

**Comment by CHCOOBOO** [comment]
This issue Just on only in Gpose

**Comment by CHCOOBOO** [comment]
![brio on](https://github.com/user-attachments/assets/de947672-f9bb-4db3-8f47-849a5ecacbba)
![brio off](https://github.com/user-attachments/assets/ab1a87d2-d57d-4992-8c6b-789f47fb2f22)

The temporary solution for now is to use the /xlplugins command to temporarily disable Brio before adjusting the wetness effect settings

**Comment by Minmoose** [comment]
Brio's wetness settings in the Advanced Appearance Window overrides FFXIV's wetness settings, this isn't going to be fixable so be sure to use Brio's not FFXIVs!
![image](https://github.com/user-attachments/assets/4dc5bdac-c34f-417b-9664-a5207cccea17)
