### ISSUE TITLE
Unable to add new actors upon installation

### ISSUE THREAD

**Issue by astralkyouki** [Etheirys/Brio#97]
I followed the tutorial and installed Brio for the first time. However, when I open the interface I am unable to add a new actor. Right clicking "Actors" does not open any options, and instead my mouse pointer turns into a black circle. Furthermore, all buttons at the bottom (including the plus sign) are grayed out
![brio interface](https://github.com/user-attachments/assets/108a8ba8-6623-4745-bd6c-69b2e26adcc6)

**Comment by Minmoose** [comment]
You must be in Gpose to spawn actors
